### ISSUE TITLE
Your application is crashing

### ISSUE THREAD

**Issue by ahmad2smile** [leveluptuts/fullstack-graphql-apollo-react-meteor#1]
I just cloned the repo `cd` into `end of #2` ran `meteor` and it errors out.

    => Started MongoDB.
    /fullstack-graphql-apollo-react-meteor/end of                             
     #2/.meteor/local/build/programs/server/boot.js:467
    W20180103-16:10:49.482(5)? (STDERR) }).run();
    W20180103-16:10:49.482(5)? (STDERR)    ^
    W20180103-16:10:49.482(5)? (STDERR) 
    W20180103-16:10:49.483(5)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules 
    W20180103-16:10:49.483(5)? (STDERR) directory. Please run the following command to install it:
    W20180103-16:10:49.483(5)? (STDERR) 
    W20180103-16:10:49.483(5)? (STDERR)   meteor npm install --save babel-runtime
    W20180103-16:10:49.484(5)? (STDERR) 
    W20180103-16:10:49.484(5)? (STDERR)     at babel-runtime.js (packages/babel-runtime.js:36:9)
    W20180103-16:10:49.484(5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
    W20180103-16:10:49.484(5)? (STDERR)     at require (packages/modules-runtime.js:238:16)
    W20180103-16:10:49.484(5)? (STDERR)     at packages/babel-runtime.js:155:15
    W20180103-16:10:49.484(5)? (STDERR)     at packages/babel-runtime.js:166:3

I don't use meteor so not much Idea what to do here.

**Comment by ahmad2smile** [comment]
Got it working with

    meteor npm install --save babel-runtime
